module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.interface.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  moduleNameMapper: {
    '^@types$': '<rootDir>/src/types',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@enums$': '<rootDir>/src/enums',
    '^@enums/(.*)$': '<rootDir>/src/enums/$1',
    '^@constants$': '<rootDir>/src/constants',
    '^@constants/(.*)$': '<rootDir>/src/constants/$1',
    '^@utils$': '<rootDir>/src/utils',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@parsers$': '<rootDir>/src/parsers',
    '^@parsers/(.*)$': '<rootDir>/src/parsers/$1',
    '^@generators$': '<rootDir>/src/generators',
    '^@generators/(.*)$': '<rootDir>/src/generators/$1',
    '^@validators$': '<rootDir>/src/validators',
    '^@validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@errors$': '<rootDir>/src/errors',
    '^@errors/(.*)$': '<rootDir>/src/errors/$1',
    '^@schemas$': '<rootDir>/src/schemas',
    '^@schemas/(.*)$': '<rootDir>/src/schemas/$1',
  },
  verbose: true,
};
