/**
 * CNAB240 Segment P schema
 */

import { z } from 'zod';
import {
  BankCodeSchema,
  BatchNumberSchema,
  RecordSequenceSchema,
  RecordTypeDetailSchema,
} from './shared';

export const SegmentPSchema = z.object({
  bankCode: BankCodeSchema,
  batchNumber: BatchNumberSchema,
  recordType: RecordTypeDetailSchema,
  sequentialNumber: RecordSequenceSchema,
  segmentCode: z.literal('P'),
  cnabReserved1: z.string().optional(),
  occurrenceCode: z.string().min(1, 'Occurrence code is required'),
  agency: z.string().min(1, 'Agency is required'),
  agencyDigit: z.string().optional(),
  account: z.string().min(1, 'Account is required'),
  accountDigit: z.string().min(1, 'Account digit is required'),
  fullAccountDigit: z.string().optional(),
  ourNumber: z.string().min(1, 'Our number is required'),
  ourNumberDigit: z.string().optional(),
  portfolioCode: z.string().min(1, 'Portfolio code is required'),
  formType: z.string().optional(),
  slipNumber: z.string().optional(),
  slipNumberDigit: z.string().optional(),
  issuanceType: z.string().optional(),
  distributionType: z.string().optional(),
  documentNumber: z.string().min(1, 'Document number is required'),
  dueDate: z.date(),
  amount: z.number().nonnegative(),
  collectionAgency: z.string().optional(),
  collectionAgencyDigit: z.string().optional(),
  speciesCode: z.string().min(1, 'Species code is required'),
  acceptance: z.string().min(1, 'Acceptance is required'),
  issueDate: z.date(),
  interestCode: z.string().optional(),
  interestDate: z.date().optional(),
  interestAmount: z.number().nonnegative().optional(),
  discountCode: z.string().optional(),
  discountDate: z.date().optional(),
  discountAmount: z.number().nonnegative().optional(),
  iofAmount: z.number().nonnegative().optional(),
  rebateAmount: z.number().nonnegative().optional(),
  protestCode: z.string().optional(),
  protestDays: z.number().int().nonnegative().optional(),
  writeOffCode: z.string().optional(),
  writeOffDays: z.number().int().nonnegative().optional(),
  currencyCode: z.string().regex(/^\d{2}$/, 'Currency code must be 2 digits'),
  companyIdentification: z.string().optional(),
  contractNumber: z.string().optional(),
  agreementNumber: z.string().optional(),
  cnabReserved2: z.string().optional(),
});
