import type { Cnab240File } from '../../src/types';

export const createMinimalCnab240File = (includeSegmentR = true): Cnab240File => ({
  fileHeader: {
    bankCode: '341',
    batchNumber: '0000',
    recordType: '0',
    companyRegistrationType: '2',
    companyRegistrationNumber: '12345678000195',
    agency: '1234',
    agencyDigit: '5',
    account: '123456',
    accountDigit: '7',
    companyName: 'ACME Corp',
    bankName: 'BANCO ITAU SA',
    fileCode: '1',
    generationDate: new Date('2026-01-15'),
    sequentialNumber: 1,
    layoutVersion: '087',
  },
  batches: [
    {
      header: {
        bankCode: '341',
        batchNumber: 1,
        recordType: '1',
        operationType: 'C',
        serviceType: '01',
        companyRegistrationType: '2',
        companyRegistrationNumber: '12345678000195',
        agency: '1234',
        agencyDigit: '5',
        account: '123456',
        accountDigit: '7',
        companyName: 'ACME Corp',
      },
      details: [
        {
          segmentP: {
            bankCode: '341',
            batchNumber: 1,
            recordType: '3',
            sequentialNumber: 1,
            segmentCode: 'P',
            occurrenceCode: '01',
            agency: '1234',
            agencyDigit: '5',
            account: '123456',
            accountDigit: '7',
            fullAccountDigit: '8',
            ourNumber: '12345678901234567890',
            portfolioCode: '109',
            documentNumber: 'DOC001',
            dueDate: new Date('2026-02-15'),
            amount: 100.5,
            collectionAgency: '0',
            collectionAgencyDigit: '',
            speciesCode: '01',
            acceptance: 'N',
            issueDate: new Date('2026-01-15'),
            interestCode: '0',
            interestDate: new Date('2026-02-16'),
            interestAmount: 0,
            discountCode: '0',
            discountDate: new Date('2026-02-10'),
            discountAmount: 0,
            iofAmount: 0,
            rebateAmount: 0,
            protestCode: '3',
            protestDays: 0,
            writeOffCode: '0',
            writeOffDays: 0,
            currencyCode: '09',
          },
          segmentQ: {
            bankCode: '341',
            batchNumber: 1,
            recordType: '3',
            sequentialNumber: 2,
            segmentCode: 'Q',
            occurrenceCode: '01',
            payerRegistrationType: '1',
            payerTaxId: '12345678901',
            payerName: 'John Doe',
            payerAddress: 'Street Test 123',
            payerNeighborhood: 'Centro',
            payerPostalCode: '12345678',
            payerCity: 'Sao Paulo',
            payerState: 'SP',
          },
          ...(includeSegmentR
            ? {
                segmentR: {
                  bankCode: '341',
                  batchNumber: 1,
                  recordType: '3',
                  sequentialNumber: 3,
                  segmentCode: 'R',
                  occurrenceCode: '01',
                  discount2Code: '0',
                  fineCode: '0',
                },
              }
            : {}),
        },
      ],
      trailer: {
        bankCode: '341',
        batchNumber: 1,
        recordType: '5',
        totalRecords: includeSegmentR ? 5 : 4,
      },
    },
  ],
  fileTrailer: {
    bankCode: '341',
    batchNumber: '9999',
    recordType: '9',
    totalBatches: 1,
    totalRecords: includeSegmentR ? 7 : 6,
  },
});
